language: python
python:
  - "3.7"

cache:
  directories:
    - "~/.platformio"
    - "$HOME/.cache/pip"

env:
  - PLATFORMIO_CI_SRC=Code/Operating System/Regular

install:
  - pip install -U platformio

  # Libraries from PlatformIO Library Registry :
  # ArduinoJson : https://platformio.org/lib/show/64/ArduinoJson/installation
  - pio lib -g install 64

script:
  - pio ci --project-conf=/Code/Operating System/platoformio.ini