language: python
python:
  - "3.7"

cache:
  directories:
    - "~/.platformio"
    - "$HOME/.cache/pip"

env:
  - LINUX_SRC=linux
  
  - PLATFORMIO_CI_SRC=Code/Operating_System/Espressif_32

install:
  - pip install -U platformio
  - pio update

  # Libraries from PlatformIO Library Registry :
  # ArduinoJson : https://platformio.org/lib/show/64/ArduinoJson/installation
  - pio lib -g install 64

script:
  - platformio ci --project-conf=/Code/Operating_System/Espressif_32/platformio.ini