language: python


python:
  - "3.7"

cache:
  directories:
    - "~/.platformio"
    - "$HOME/.cache/pip"

env:
  # - LINUX_SRC=linux
  
  - PLATFORMIO_CI_SRC=Code/

install:
  - pip install -U platformio
  - pio update

  # Libraries from PlatformIO Library Registry :
  # ArduinoJson : https://platformio.org/lib/show/64/ArduinoJson/installation
  - pio lib -g install 64

script:
  - pio run --project-dir="./Code/"